<%@ Page Title="Chatta: Chat Hub" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="User.aspx.cs" Inherits="Chatta.Account.User" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div id="whole-box-header">
        <div class="groupchat-header"></div>
        <div class="userbox-header"></div>
    </div>
    <div id="whole-box">
        <div class="groupChat-box">
            <div class="chat-area">
                <!-- This the main content of the group chat -->
                <input type="hidden" id="Email" />
                <ul id="chat-container" style="list-style-position:inside">
                </ul>
            </div>
                <div class="lower-left">
                <div class="msg-box">
                    <textarea id="Textbox1" placeholder="Type your message here"></textarea>
                </div>
                <div class="send-box">
                    <!-- Some issues with running Button controller on the server side and firing javascript at the same time 
                    <asp:Button ID="btnSend" class="btn btn-primary btn-lg" runat="server" Height="100%" Text="Send" ToolTip="Send Message" Width="100%"/>
                    -->
                    <input id="sendButton" class="btn btn-primary btn-lg" style="height:100%; width:100%" type="button" value="Send" />
                    <!--Script references. -->
                    <!--Reference the jQuery library. -->
                    <script src="/Scripts/jquery-3.1.1.min.js"></script>
                    <!--Reference the SignalR library. -->
                    <script src="/Scripts/jquery.signalR-2.2.1.js"></script>
                    <!--Reference the autogenerated SignalR hub script. -->
                    <script src="/signalr/hubs"></script>
                    <!--Add script to update the page and send messages.-->
                    <script type="text/javascript">
                        $(function ()
                        {
                            // Declare a proxy to reference the hub(ChatHub will be reference using camelCase (chatHub)).
                            var chat = $.connection.chatHub;
                            // Create a function that the hub can call to broadcast messages.
                            chat.client.broadcastMessage = function (email, message)
                            {
                                // Html encode display email, message, and time.
                                var encodedEmail = '<%=Context.User.Identity.GetUserName()%>'; //This is the current user
                                var encodedMsg = document.getElementById("Textbox1").value;
                                var encodedTime = new Date().toLocaleTimeString();
                                // Add the message to the page.
                                $('#chat-container').append('<li>' + encodedEmail + '&nbsp;&nbsp;' + encodedMsg + '&nbsp;&nbsp' + encodedTime + '</li>');
                            };
                            //Get the current user identity
                            $('#Email').val() = '<%: Context.User.Identity.GetUserName()  %>';
                            // Set initial focus to message input box.
                            $('#TextBox1').focus();
                            // Start the connection.
                            $.connection.hub.start().done(function ()
                            {
                                $('#sendButton').click(function ()
                                {
                                    // Call the Send method on the hub.
                                    chat.server.send($('#Email').val(), $('#TextBox1').val());
                                    // Clear text box and reset focus for next message.
                                    $('#TextBox1').val('').focus();
                                });
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
        <div class="user-box">
            <ul style="list-style-position:inside">
                <li><%: Context.User.Identity.GetUserName()  %></li>
            </ul>
        </div>
    </div>
</asp:Content>
